### ISSUE TITLE
Trabajo de fin de semana colaborativo:

### ISSUE THREAD

**Issue by VaniushaR** [VaniushaR/cdmx-2018-06-bc-core-am-data-dashboard#24]
**(DoD) Definition of Done:** 
-Terminar la funcionalidad de 1ª Función al menos hasta Topics. Incluye Stats. @MicheleBecerra 
-Testing @MicheleBecerra 
-Organizar Readme (Vania)
-Visual Design Bootstrap (Vania)
-Empezar funcionalidad 2da Función (Vania)
-Actualización de issues (ambas)

**Espectativa para el lunes:**

-Empezar a pintar en el DOM juntas. 
-Limpieza de código y estilo.
-Definir y decidir juntas  los alcances máximos que hemos logrado con buena funcionalidd.
-Practicar DEMO.

_"Hace una semanas no eramos capaces de escribir una línea de código, hoy llevamos más de 500"_

> Trabajar en equipo es la mejor manera de hacer el trabajo. <3

**Comment by MicheleBecerra** [comment]
Definition of Done

Respecto al desarrollo de la función 1, se logro imprimir en consola topics y subtopics.
Tengo que trabajar con el Boostrap para terminar la interfaz.
Hacer dinámico el prototype.

"El remedio más efectivo para la ansiedad es la toma de decisiones"
