### ISSUE TITLE
Feedback Datadashboard

### ISSUE THREAD

**Issue by nerdale** [VaniushaR/cdmx-2018-06-bc-core-am-data-dashboard#31]
Queridas @VaniushaR y @MicheleBecerra 
Estuve revisando el proyecto entregado y tengo algunos comentarios:

1. Felicitaciones por no rendirse y continuar, espero que el aprendizaje sea bueno y que retomen el proyecto más adelante para que aparezca en un futuro en sus portafolios. :clap: 

2. Es poco lo que puedo decir en cuanto a funcionalidad del datadashboard, de todo lo que debía mostrar no se visualiza nada, solo la simulación del login.

3. Me preocupa y llama profundamente la atención errores pequeños, esenciales y básicos que no solucionaron, especificamente en el archivo **index.html** incluso si hubiesen probado los test de html que sale en la rúbrica, se hubiesen dado cuenta que tienen 107 errores en uno (htmlhint) y 28 en otro (validator w3)., como por ejemplo usar mezclas de comillas simples y dobles, las dobles van en los archivos HTML, es un estándar de google y sus motores de búsqueda, o por ejemplo de la línea 127 a la 131, todos esos scripts están dentro de `<main>` eso es incorrecto, debe ser justo antes de `<body>`
Me parece que es un tema del que deben tomar medidas ahora ya, es preocupante no manejar esos detalles. Acerquense a los coaches si necesitan ayuda personalizada.

4. Se ve estudio de usuario y se agradece documentar la entrevista con video, pero estos son muy cortos y no logran ser una muestra real de como se llevo a cabo esta, tampoco documentan que preguntas hacen, que respuestas obtienen, a cuantos usuarios entrevistan, uno solo? 

5. Sobre color y alineación no es mucho lo que puedo decir porque es poco lo que se puede ver, solo me surge la duda, si estaban guiandose por los colores corporativos, porque la decisión de usar azul? todo eso debería estar sustentado por su investigación de usuario.

6. Se nota trabajo colaborativo en github, eso si, aprovechen los milestones, solo los hicieron y ahí quedaron. Por esta vez lo paso por alto.

Se que tuvieron mil problemas entre esos de comunicación, espero que los hayan superado o al menos trabajado en eso, aprendan de esta experiencia para trabajos futuros :smile:

**Comment by VaniushaR** [comment]
Gracias Alexandra, aprendí mucho de este proyecto. Creo que cada una debemos mejorar el proyecto para nuesto portafolio, lo haremos en los días de revisión o cuando nos lo pidan. Te agradezco mucho el feedback. Saludos hasta Chile.

**Comment by nerdale** [comment]
:smile: Vamos con power!!
