### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [VaniushaR/cdmx-2018-06-bc-core-am-data-dashboard#9]
Hola @VaniushaR y Compañera
He estado revisando el proyecto y tengo algunos comentarios:

1. @VaniushaR debes agregar como colaboradora a **MichBecerra**, es extremadamente necesario pues los issues van guiados hacia ambas.

2. Deben participar ambas en los issues y milestones de cada sprint, solo veo a @VaniushaR interactuar.

3. Buena investigación de ux, eso si hay una carpeta llamada **ux** donde viene un readme detallado con todo el proceso de UX que deberían comentar y en ese readme específico.

4. No hay mucha lógica, salvo un llamado fetch. Les recomiendo entrar de lleno a la data lo antes posible y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

5. En el archivo **index.html** utilizan unas etiquetas `<br>` para saltos de línea, eso no es necesario, los `<input>` son elementos de tipo **inline** así que puedes modificarles el display en css y tendrás el mismo efecto sin tener que utilizar esas etiquetas.

6. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

7. Buen trabajo colaborativo en github.

Vamos vamos!! a darlo todo, ustedes puedeeeen :metal: :muscle:

**Comment by VaniushaR** [comment]
Gracias @nerdale  :)

**Comment by MicheleBecerra** [comment]
Gracias @nerdale  por tu feedback, ya empezamos a tomar tus sugerencias de cabios.

**Comment by nerdale** [comment]
Perfecto, cerraré el issue entonces.
:rocket:
